services:
  - type: web
    name: novaria
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: GROQ_KEY
        sync: false
      - key: OPENROUTER_KEY
        sync: false
